# Generated by Django 2.1.2 on 2018-11-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='jsonfile',
            field=models.FileField(default=0, upload_to='jsons/'),
        ),
    ]
