# Generated by Django 2.1.2 on 2018-11-07 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='BlogsPost',
        ),
        migrations.RenameField(
            model_name='blogspost',
            old_name='titile',
            new_name='title',
        ),
    ]
