# Generated by Django 2.1.2 on 2018-11-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181107_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classid', models.CharField(max_length=150)),
                ('jsonfile', models.FileField(upload_to='')),
            ],
        ),
    ]
