# Generated by Django 2.1.2 on 2018-11-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_jsonpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsonpost',
            name='jsonfile',
            field=models.FileField(upload_to='json/'),
        ),
    ]
